#!/bin/bash

usage="Usage: $0 <source> <destination>"
if [ "$#" -ne 2 ]; then
  echo $usage >&2
  exit 1
fi

filename=$(basename $1)
if [ -d "$2" ]; then
  destination="$2"/"$filename"
elif [ -e "$2" -o "${2: -1}" != "/" ]; then
  destination="$2"
else
  mkdir -p $2
  destination="$2"/"$filename"
fi

mv "$1" "$destination"
ln -sr "$destination" "$1"
