set-option -g default-shell /bin/zsh

# Setup clipboard support, reference: https://github.com/tmux/tmux/wiki/Clipboard
# set -s copy-command 'wl-copy'
# For X11
# set -s copy-command 'xsel -i'
set -g set-clipboard on
set -g focus-events on

bind -T copy-mode    v                 send -X begin-selection
bind -T copy-mode    C-w               send -X copy-selection-and-cancel
bind -T copy-mode    M-w               send -X copy-selection-and-cancel
bind -T copy-mode    MouseDragEnd1Pane send -X copy-selection-and-cancel

bind -T copy-mode-vi v                 send -X begin-selection
bind -T copy-mode-vi y                 send -X copy-selection-and-cancel
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-and-cancel

# bind C-c run "tmux save-buffer - | xclip -i -sel clipboard"

set -g history-limit 40960
set -s escape-time 0
set -g status-interval 0
set -g base-index 1
set -g default-terminal "tmux-256color"

## split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

## select pane (move like vim)
bind -r k select-pane -U # above (prefix k)
bind -r j select-pane -D # below (prefix j)
bind -r h select-pane -L # left (prefix h)
bind -r l select-pane -R # right (prefix l)
## resize pane (resize like vim)
bind -r ^k resizep -U 10 # upward (prefix Ctrl+k)
bind -r ^j resizep -D 10 # downward (prefix Ctrl+j)
bind -r ^h resizep -L 10 # to the left (prefix Ctrl+h)
bind -r ^l resizep -R 10 # to the right (prefix Ctrl+l)

## easy to swich window, like byobu
bind-key -n F2 new-window
bind-key -n F3 previous-window
bind-key -n F4 next-window

## configure file reload
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

## style
set-option -g status-keys vi
set-window-option -g mode-keys vi
